# Welcome to numpy tutorial!

In [1]:
import numpy as np

In [13]:
myarr= np.array([ [3, 6, 323333333339, 7 ]], np.int64) #memory allocation is in your hands


In [11]:
myarr

array([           3,            6, 323333333339,            7])

In [18]:
myarr [0,1] # 0th row and 1st column is 6

np.int64(6)

In [19]:
myarr [0,0] #0th row and 0th column is 3

np.int64(3)

In [20]:
myarr.dtype

dtype('int64')

In [23]:
myarr [0,1]=45 #changed element at 0,1

In [22]:
myarr

array([[           3,           45, 323333333339,            7]])

In [24]:
x = [[1, 2, 3], [4,5,6], [7,1,0]]

In [27]:
ar= np.array(x)

In [28]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [29]:
ar.sum(axis=0) #vertical summation, axis 0

array([12,  8,  9])

In [30]:
ar.sum(axis=1) #horizontal summation, axis 1

array([ 6, 15,  8])

In [32]:
ar.T #Transpose of ar

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [33]:
ar.flat

In [37]:
for item in ar.flat:
    print (item)

1
2
3
4
5
6
7
1
0


In [38]:
ar.ndim #No. of dimensions

2

In [39]:
ar.size #size of array

9

In [41]:
ar.nbytes #total bytes consumed by the elements of the array

72

In [49]:
one = np.array([1,2,3,8,6])

In [50]:
one.argmax()

np.int64(3)

In [51]:
one.argmin()

np.int64(0)

In [52]:
one.argsort()

array([0, 1, 2, 4, 3])

In [53]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [54]:
ar.argmin()

np.int64(8)

In [55]:
ar.argmax()

np.int64(6)

In [57]:
ar.argmax(axis=0)

array([2, 1, 1])

In [59]:
ar.argmax(axis=1)

array([2, 2, 0])

In [60]:
ar.ravel() #brings all in one line

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [84]:
ar.reshape(3,3)

array([[ 4,  0, 16],
       [24, 12, 20],
       [ 4,  0,  4]])

In [85]:
ar2= np.array([[1,0,4],[6,3,5],[1,0,1]])